services:
  carsdb:
    image: ankane/pgvector:latest
    container_name: rag_db
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Use local ./pgdata folder
    restart: always


volumes:
  pgdata: